 const URLS = {
  Login: "/logincms",
  PrimaryCategory: "/primary-category",
  AddPrimaryCategory: "/add-primary-category",
  Dashboard: "/dashboard",
  EditPrimaryCategory: "/edit-primary-category",
  ChangePassword: "/change-password",
  SecondaryCategory: "/secondary-category",
  AddSecondaryCategory: "/add-secondary-category",
  EditSecondaryCategory: "/edit-secondary-category",
  VehicleManagement: "/vehicle-management",
  EditVehicleData: "/edit-vehicle-data",
  RpiManagement: "/rpi-managemet",
  EditRpiList: "/edit-rpi-management",
  AddRpiManagement: "/add-rpi-management",
	ArvalManagement: "/arval-management",
  TertiaryCategory : "/tertiary-category",
  AddtertiaryTag : "/add-tertiary-tag",
  EditTertiaryTag : "/edit-tertiary-tag",
  TheElectricRevolution : "/the-electric-revolution",
  OurMission : "/our-mission",
  ElectricVehicleEvGuide : "/electric-vehicle-ev-guide",
  Partners : "/partners",
  EvCharges : "/ev-charges",
  Hyrdrogen : "/hydrogen-vehicle-guide",
  HybridVehicleHevGuide : "/hybrid-vehicle-hev-guide",
  FullElectric : "/fullelectric",
  TermsAndCondition : "/terms-and-condition",
  Cookie : "/cookie",
  PrivacyAndPolicy : "/privacy-and-policy",
  LeasingExplained : '/leasing-explained',
  PlugInHybridPhevGuide : '/plug-in-hybrid-phev-guide',
  BuyingCar : '/buying-car',
  SellingCar : '/selling-car',
  ChargingGuide : '/charging-guide',

};

export default URLS;
